# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coveo Cloud V2 Docs
email: DevDocSiteAdmin@coveo.com
description: > # this means to ignore newlines until "baseurl:"
  Coveo Cloud API documentation.

# The site base protocol & hostname (e.g. http://example.com (used by jekyll-sitemap))
url: "https://d3in5cp0cx0iu6.cloudfront.net"

# Needed for relative links to work in GitHub pages (ex.: "/cloudv2-docs-site") adding {{ site.baseurl }} to all links
baseurl: ""

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md
  - CONTRIBUTING-CONTENT.md

collections:
  glossary:
    output: true
  api-explorer:
    output: true
