---
  debug: True # Setting this to False will execute the script in "silent" mode.
  repository:
    accessToken: "" # Must allow to create PRs on public GitHub repositories. Leave empty for now.
    tempOutputJsonPath: ./temp_json/ # Where to save temporary JSONs when running diff script. Deleted after script.
    outputYamlPath: ../../api_docs_test/ # Where the YAML API specifications are stored.
    mdPagesPath: ../../_api-explorer/ccv2/ # Where to put the MD pages.
    mdLayout: redoc_page # Use either "redoc_page", "swaggerui2_page" or "swaggerui3_page".
    upstreamBranch: upstream_update_test_2 # The branch that the diff script checkouts when it runs.
    baseBranch: master # The deploy script checkouts this branch. The diff script sends its PRs to this branch.
    baseUpstreamCommitMessage: Upstream_update_ # Base commit message used by the diff script. Datetime is added.
    baseDeployCommitMessage: Deployment_ # Base commit message used by the deploy script. Datetime is added.
    upstreamPullRequestMessage: Upstream_update_request # PR message used by the diff script.
  platform:
    environment: "" # Use either "" (for Prod environment), "qa" or "dev".
    apiList: # The list of apis to try to load from the Coveo platform site.
      - Platform
      - Index
      - Field
      - SecurityCache
      - Source
      - Activity
      - UsageAnalyticsRead
      - UsageAnalyticsWrite
      - PushApi
      - SourceLogsApi
      - Extension
      - AuthorizationServer
      - Notification
      - SearchApi
    methodList: # The list of methods allowed by the Swagger specification.
      - get
      - put
      - post
      - delete
      - options
      - head
      - patch
    host1: https://platform # The "environment" variable will be added between "host1" and "host2".
    host2: .cloud.coveo.com
    apiDocsPath: /api-docs/ # This is where the JSON specs are on the Coveo platform site.

